### ISSUE TITLE
Schedule with crontab

### ISSUE THREAD

**Issue by albertopasqualetto** [layou233/NeverIdle#11]

**Comment by yoshyv** [comment]
这个没必要cron
弄个守护进程后台一直跑就行。

**Comment by albertopasqualetto** [comment]
I know it is not necessary, but in my systems, I prefer using cron.

**Comment by layou233** [comment]
Cron is easy to use and you can use it with `timeout` command. So there is no need for me to change anything. :-)

**Comment by albertopasqualetto** [comment]
Thanks
