### ISSUE TITLE
当运行时长一段时间，出错退出

### ISSUE THREAD

**Issue by wxdjs** [layou233/NeverIdle#13]
[CPU] Successfully wasted on 2023-02-21 22:57:18.687024367 +0000 UTC m=+1850408.314042512
panic: chacha20: counter overflow

goroutine 52850 [running]:
golang.org/x/crypto/chacha20.(*Cipher).XORKeyStream(0xc000108160?, {0xc000180000?, 0xc000147b80?, 0xc000880b40?}, {0xc000180000?, 0x6ed310?, 0xc0008f8600?})
	golang.org/x/crypto@v0.5.0/chacha20/chacha_generic.go:218 +0x408
main.WasteCPU.func1()
	NeverIdle/cpu.go:30 +0x48
created by main.WasteCPU
	NeverIdle/cpu.go:28 +0x1e5
 Ubuntu 18.04.4 LTS (GNU/Linux 5.4.0-1066-oracle x86_64)

**Comment by layou233** [comment]
Try 0.2 release.
