### ISSUE TITLE
关于CPU占用

### ISSUE THREAD

**Issue by yoshyv** [layou233/NeverIdle#14]
请问这个CPU消耗能指定线程数吗
每次消耗会跑多少时间呢？
如果只是突发的高占用可能被95百分位数忽略？
能考虑弄个限制CPU使用率吗。比如设置常年占用10%就不用指定间隔，一直跑就好了。

**Comment by layou233** [comment]
CPU 占用并不好估算，实际上都是按经验来的，不同的 CPU （甚至同一款 CPU 在不同机房）性能都不一样，因此写个 CPU 使用率限制其实并不容易，不过或许可以写个指定工作量然后让用户自己调值？

如果需要一直占用的话，可以把时间间隔放的短一点。

**Comment by fanthos** [comment]
我觉得可以计时来计算工作量，不限制cpu

**Comment by layou233** [comment]
更新了新的 `-cp` 参数，可以控制用量了。
