### ISSUE TITLE
CPU usage inadequate 

### ISSUE THREAD

**Issue by Paul-Reed** [layou233/NeverIdle#25]
I'm using a 4 core VM.Standard.A1.Flex, and also your NeverIdle-linux-arm64 script, and noticed that the CPU activity does not reach the 95th Percentile target set by Oracle.
Even if the CPU feature was set to run `-c 1m`, it would still not reach the 95th Percentile target, as it only runs for less than a minute each time, and then only reached 8% at it's peak, and most times it's much lower.

**Comment by layou233** [comment]
We have updated a new version. Go and try `-cp`, it just fixes this issue!

**Comment by Paul-Reed** [comment]
Thank you
