### ISSUE TITLE
建议在代码里设置一下进程的nice值，优先级最低，并且尽量不要跑满cpu

### ISSUE THREAD

**Issue by fannwong001** [layou233/NeverIdle#28]
刚看了下nice值和普通程序是一样的都是0，还得手动renice修改，go语言里应该也有nice函数可以实现吧。
cpu好像也是双核跑了20秒。我觉得占多少cpu最好可以由用户设置。至少可以控制跑几个线程。

**Comment by layou233** [comment]
最新版实现了全平台设置优先级功能，在 Linux 下可以设置 nice （默认还能设置 ioprior 为最低）。欢迎测试！

**Comment by fannwong001** [comment]
> 最新版实现了全平台设置优先级功能，在 Linux 下可以设置 nice （默认还能设置 ioprior 为最低）。欢迎测试！

ok晚上试试
