### ISSUE TITLE
arm机器的测速都是没有显示结果

### ISSUE THREAD

**Issue by wxdjs** [layou233/NeverIdle#4]
看了两台arm机器，好像都没有显示，一些数据如下：

[NETWORK] SpeedTest Ping: 152.278863ms , 2.1863757762040916 , Upload: 0.6479155546829458 via [37235]  8331.62km 
Shenyang (China) by Unicom

[NETWORK] SpeedTest Ping: 84.991532ms , 34.01522008046169 , Upload: 37.481146947397846 via [37235]  8331.62km 
Shenyang (China) by Unicom

[NETWORK] SpeedTest Ping: 124.063885ms , -1 , Upload: -1 via [37235]  8331.62km 
Shenyang (China) by Unicom
[NETWORK] SpeedTest Ping: -1ns , -1 , Upload: -1 via [5249]     2.21km 
Seoul (South Korea) by Ookla

[NETWORK] SpeedTest Ping: -1ns , -1 , Upload: -1 via [5249]     2.21km 
Seoul (South Korea) by Ookla

[NETWORK] SpeedTest Ping: -1ns , -1 , Upload: -1 via [5249]     2.21km 
Seoul (South Korea) by Ookla

**Comment by Ansen** [comment]
我使用一键脚本安装的没问题

> AMD

![image](https://user-images.githubusercontent.com/676412/215941272-b0c51389-769a-4b2a-88a5-b78e87bc9d01.png)

> ARM

![image](https://user-images.githubusercontent.com/676412/215941383-51267ae3-321c-4e9a-b339-dbdf1c67c7dd.png)

**Comment by wxdjs** [comment]
有的arm可以，有的就不行，都是一键，系统都是ubuntu，奇怪了，这个需要开启什么端口吗？

**Comment by Ansen** [comment]
> 有的arm可以，有的就不行，都是一键，系统都是ubuntu，奇怪了，这个需要开启什么端口吗？

不需要开啥端口，测速这个就是speedtest.net的测速而已

**Comment by wxdjs** [comment]
我直接下载speedtest-go，运行是这种显示结果
root@instance-20220824-1057:/home/ubuntu# ./speedtest-go 
Testing From IP:  xxxx , (Oracle Cloud) [37.5794, 126.9754] 
 
Target Server: [6527]     2.21km Seoul (South Korea) by kdatacenter.com
Latency: 19.766204ms
Download Test: ...................................
Upload Test: ...
 
Download:  0.52 Mbit/s
Upload: 604.41 Mbit/s

**Comment by kang000feng** [comment]
> > 有的arm可以，有的就不行，都是一键，系统都是ubuntu，奇怪了，这个需要开启什么端口吗？
> 
> 不需要开啥端口，测速这个就是speedtest.net的测速而已

请教用您的脚本如何修改测速节点? 我我也碰到了跟楼主一模一样的问题, 现在初步判断是这个测速节点不可用

**Comment by r3inbowari** [comment]
#9 We have fixed this issue upstream. Thank you.
