### ISSUE TITLE
下载好程序后如何使用，小白请教

### ISSUE THREAD

**Issue by liuwleo** [layou233/NeverIdle#5]
下载好程序后如何使用，小白请教，谢谢。

**Comment by yimouleng** [comment]
# 下载编译后的可执行文件
# AMD服务器
wget https://github.com/layou233/NeverIdle/releases/download/0.1/NeverIdle-linux-amd64 -O NeverIdle

# ARM
wget https://github.com/layou233/NeverIdle/releases/download/0.1/NeverIdle-linux-arm64 -O NeverIdle

# 修改文件权限
chmod 777 NeverIdle

# 使用screen运行程序
screen -R baohuo

# 启动程序
./NeverIdle -c 2h -m 2 -n 4h

# 挂起screen 按 Ctrl+A+D

#再次进入screen 
screen -R baohuo
