### ISSUE TITLE
每次运行都会多出一个进程

### ISSUE THREAD

**Issue by PotatoYummy** [layou233/NeverIdle#73]
RT，本人ARM A1实例(2ocpu 24G)，目前使用宝塔面板的计划任务执行该脚本（因为不懂代码），已将脚本参数设置为 -cp 0.3 -m 2 -n 2h，如下图所示
![搜狗截图20231210070557](https://github.com/layou233/NeverIdle/assets/86452004/42253851-9c72-4e94-ab16-20e85da46344)
运行后cpu占用、内存占用都在30左右、网络测速也正常进行。感谢开发者的无私分享。但有些疑问：
1. 计划任务里已经定义了运行脚本的时间间隔，脚本本身也有个-n两小时的时间间隔，叠加在一起的话会怎么计算的。我看Oracle最新的要求已经变成了内存、CPU、网络使用率最低需要95%时间>20%了，我这里的设置是否能满足需求呢？
2. 我发现脚本每执行一次，系统就会多出一个相同的NerverIdle-linux进程，如此CPU和内存越越来越大，直到超过80%收到告警，然后为了避免100%我每次都要手动kill一下多出来的重复进程。所以按我的理解这个脚本只要跑起来就已经起到了CPU和内存占用的目的，似乎没必要一直重复去运行它？就是测速是一次性的，可能需要隔段时间去运行一次。如果是这样的话，那我应该怎么去设定这个计划呢（不知道我的理解是否有问题）
以上，希望有大佬帮忙解答一下，谢谢！！

**Comment by layou233** [comment]
不需要配合第三方“定时执行”之类的功能使用。只需启动一个 NeverIdle 并保持它不被杀死（或者杀死后自动重启），它就会按照设定的间隔自己不断执行下去。相当于内置了定时执行。

这样设计是因为，像内存占用那样的功能不适合配合定时执行使用，因为只需一直保持内存占用就行了。

**Comment by PotatoYummy** [comment]
@layou233 清楚了！感谢解答，已经删除该计划任务，并将该脚本做了进程守护
![微信截图_20231210105227](https://github.com/layou233/NeverIdle/assets/86452004/a6180412-f744-428b-9a5b-e14b42b3eabf)
